### ISSUE TITLE
I want to purchase your complete code

### ISSUE THREAD

**Issue by asasas234** [gianlourbano/demucs-onnx#1]
Hi, sorry, besides here, I don't know where else to contact you. I am very interested in your project, but I am not very familiar with machine learning related technologies myself. So I would like to directly purchase your complete project, including how to modify the demucs code, export the relevant scripts for onnx, as well as the final exported onnx file and a demo for calling onnx web. I am willing to pay for it. If you are interested, you can contact me by searching "asasas234123" on Telegram and we can discuss it in detail.

**Comment by gianlourbano** [comment]
I'm sorry @asasas234 , but this is company work and i obviously cannot sell it.
